spring.application.name=reactive-streaming
spring.data.mongodb.uri=mongodb+srv://<db_user>:<db_pass>@<db-uri>/?appName=devrel-tutorial-java-reactive-streaming-foojay
spring.data.mongodb.database=reactive-streaming